[package]
name = "cargo2nix"
version = "0.1.0"
edition = "2018"

[dependencies]
cargo = "0.36.0"
clap = "2.33.0"
failure = "0.1.5"
futures = "0.1"
lazy_static = "1.3.0"
regex = "1.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
tokio = "0.1.21"
tokio-process = "0.2"
toml = "0.5"
