[package]
name = "cargo2nix"
version = "0.1.0"
edition = "2018"

[dependencies]
derive_more = "0.14.0"
futures = "0.1.27"
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1.19"
tokio-process = "0.2.3"
toml = "0.5"
