[package]
name = "cargo2nix2"
version = "0.1.0"
authors = ["Trinh Hoang Anh <anh@tenx.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
once_cell = "1.2.0"
toml = "0.5.3"
serde = { version = "1.0.101", features = ["derive"] }
cargo = "0.39.0"
pathdiff = "0.1.0"
